---
abstract: 'Geocode addresses using geocoder.us'
author:
  - 'Tom Wyant (wyant at cpan dot org)'
build_requires:
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Coder-Geocoder-US
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Geo::Coder::Geocoder::US:
    file: lib/Geo/Coder/Geocoder/US.pm
    version: 0.001
requires:
  Carp: 0
  LWP::UserAgent: 0
  Text::CSV: 0
  URI::Escape: 0
  perl: 5.006002
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Geo-Coder-Geocoder-US
  license: http://dev.perl.org/licenses/
version: 0.001
